CREATE DATABASE IF NOT EXISTS 4064_4078_4107
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE 4064_4078_4107;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  mdp VARCHAR(100),
  mail VARCHAR(100),
  numero VARCHAR(100)
);

CREATE TABLE region (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(50)
);

CREATE TABLE ville (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(50),
  id_region INT,
  FOREIGN KEY (id_region) REFERENCES region(id)
);

CREATE TABLE besoin_nature (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  id_ville INT,
  FOREIGN KEY (id_ville) REFERENCES ville(id)
);

CREATE TABLE besoin_materiaux (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  id_ville INT,
  FOREIGN KEY (id_ville) REFERENCES ville(id)
);

CREATE TABLE besoin_argent (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vola DOUBLE,
  id_ville INT UNIQUE,
  FOREIGN KEY (id_ville) REFERENCES ville(id)
);

CREATE TABLE dons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_users INT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_users) REFERENCES users(id)
);

CREATE TABLE dons_nature (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  id_dons INT,
  FOREIGN KEY (id_dons) REFERENCES dons(id)
);

CREATE TABLE dons_materiaux (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100),
  id_dons INT,
  FOREIGN KEY (id_dons) REFERENCES dons(id)
);

CREATE TABLE dons_argent (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vola DOUBLE,
  id_dons INT UNIQUE,
  FOREIGN KEY (id_dons) REFERENCES dons(id)
);
